Update ffmpeg2.yml

diff --git a/.github/workflows/ffmpeg2.yml b/.github/workflows/ffmpeg2.yml
--- a/.github/workflows/ffmpeg2.yml
+++ b/.github/workflows/ffmpeg2.yml
@@ -1,27 +1,29 @@
-name: FFMPEG 2
+name: FFmpeg Job
 
 on:
   workflow_dispatch:
     inputs:
-      ffmpegcom:
-        description: 'Command ffmpeg'
+      ffmpeg_command:
+        description: 'FFmpeg command to execute'
         required: true
 
 jobs:
-  live-streaming:
+  ffmpeg:
     runs-on: ubuntu-latest
 
     steps:
-      - name: install ffmpeg
-        run: sudo add-apt-repository ppa:ubuntuhandbook1/ffmpeg7 -y > /dev/null;sudo apt update -qq > /dev/null;sudo apt install ffmpeg -y -qq > /dev/null
-      - name: live stream
-        run: 
-          #!/bin/bash
-          # Script Bash untuk menjalankan FFmpeg dan memantau statusnya
+      - uses: actions/checkout@v3
+      - name: Set up FFmpeg
+        run: |
+          sudo add-apt-repository ppa:ubuntuhandbook1/ffmpeg7 -y
+          sudo apt update -y
+          sudo apt install ffmpeg -y
+      - name: Run FFmpeg
+        run: |
           while true; do
-            ${{ github.event.inputs.ffmpegcom }}
+            ${{ github.event.inputs.ffmpeg_command }}
             if [ $? -ne 0 ]; then
-              echo "FFmpeg stopped. Restarting..."
+              echo "FFmpeg stopped with error code $?. Restarting..."
               sleep 5
             fi
           done
